// Generated by https://quicktype.io

export interface User {
  kind:               string;
  etag:               string;
  nickname:           string;
  occupation:         string;
  skills:             string;
  birthday:           string;
  gender:             string;
  emails:             Email[];
  urls:               URL[];
  objectType:         string;
  id:                 string;
  displayName:        string;
  name:               Name;
  tagline:            string;
  braggingRights:     string;
  aboutMe:            string;
  relationshipStatus: string;
  url:                string;
  image:              Image;
  organizations:      Organization[];
  placesLived:        PlacesLived[];
  isPlusUser:         boolean;
  language:           string;
  ageRange:           AgeRange;
  plusOneCount:       number;
  circledByCount:     number;
  verified:           boolean;
  cover:              Cover;
  domain:             string;
}

export interface AgeRange {
  min: number;
  max: number;
}

export interface Cover {
  layout:     string;
  coverPhoto: CoverPhoto;
  coverInfo:  CoverInfo;
}

export interface CoverInfo {
  topImageOffset:  number;
  leftImageOffset: number;
}

export interface CoverPhoto {
  url:    string;
  height: number;
  width:  number;
}

export interface Email {
  value: string;
  type:  string;
}

export interface Image {
  url: string;
}

export interface Name {
  formatted:       string;
  familyName:      string;
  givenName:       string;
  middleName:      string;
  honorificPrefix: string;
  honorificSuffix: string;
}

export interface Organization {
  name:        string;
  department:  string;
  title:       string;
  type:        string;
  startDate:   string;
  endDate:     string;
  location:    string;
  description: string;
  primary:     boolean;
}

export interface PlacesLived {
  value:   string;
  primary: boolean;
}

export interface URL {
  value: string;
  type:  string;
  label: string;
}
